---
title: "Confirm protein expression change in HPA"
output:
  html_notebook:
    code_folding: show
editor_options:
  chunk_output_type: console
---
# {.tabset .tabset-fade .tabset-pills}

## Setup
### Load libraries
```{r}
library(here)
library(tidyverse)
library(tidylog)
```

## Download normal and pathology datasets downloaded from HPA
```{r}
## Normal
url <- "https://www.proteinatlas.org/download/normal_tissue.tsv.zip"
file <- here("data", "hpa-normal.tsv.zip")

if(!file.exists(file)){
  download.file(url = url, destfile = file)
}

HPA_normal <- read_tsv(file) %>%
  janitor::clean_names()

## Pathology
url <- "https://www.proteinatlas.org/download/pathology.tsv.zip"
file <- here("data", "hpa-cancer.tsv.zip")

if(!file.exists(file)){
download.file(url = url, destfile = file)
}
HPA_pathology <- read_tsv(file) %>%
  janitor::clean_names()

rm(url); rm(file)
```

## Filter the HPA by tissue, cell type and the up- or down-regulated genes
```{r}
filterNormal <- function(genes, normal_data){
  normal_data %>%
  filter(tissue %in% c("rectum", "colon", "prostate", "breast", "lung")) %>%
  filter(cell_type %in% c("glandular cells", "pneumocytes")) %>%
  filter(gene %in% genes)
}

filterCancer <- function(genes, cancer_data){
  cancer_data %>%
  select(gene:not_detected) %>% 
  mutate(cancer = str_remove(cancer, pattern = " cancer")) %>% 
  filter(cancer %in% c("colorectal",
                       "prostate",
                       "breast",
                       "lung")) %>% 
  filter(gene %in% genes) %>%
  drop_na(high:not_detected) %>%
  mutate(n_samples = rowSums(select(., high:not_detected)))
}
  
degs_4vs2_up <- degs_4vs2 %>% filter(log2FoldChange >= 1)
normal_data_for_up <- filterNormal(genes = degs_4vs2_up$gene_id, normal_data = HPA_normal)
cancer_data_for_up <- filterCancer(genes = degs_4vs2_up$gene_id, cancer_data = HPA_pathology)
intersect(normal_data_for_up$gene, cancer_data_for_up$gene) %>% length()
  # 446 of 639 up-regulated genes have normal and pathology data

degs_4vs2_down <- degs_4vs2 %>% filter(log2FoldChange <= -1)
normal_data_for_down <- filterNormal(genes = degs_4vs2_down$gene_id, normal_data = HPA_normal)
cancer_data_for_down <- filterCancer(genes = degs_4vs2_down$gene_id, cancer_data = HPA_pathology)
intersect(normal_data_for_down$gene, cancer_data_for_down$gene) %>% length()
  # 949 of 1329 down-regulated genes have normal and pathology data

rm(normalFromHPA)
rm(cancerFromHPA)
```

## Check for differences in protein abundance between normal tissue and cancer
### Define the comparison functions
```{r}
checkIfDownregulated <- function(tissue_type, cancer_type, normal_data, cancer_data){
  
  inner_join(normal_data, cancer_data, by = "gene") %>%
    dplyr::select(gene, gene_name = gene_name.x, tissue, cancer, level, high:not_detected, n_samples) %>% 
    mutate(samples_down = case_when(level == "High" ~ 0,
                                   level == "Medium" ~ as.double(high),
                                   level == "Low" ~ as.double(high+medium),
                                   level == "Not detected" ~ as.double(high+medium+low))) %>% 
    mutate(samples_down = case_when(level == "High" ~ as.double(medium+low+not_detected),
                                   level == "Medium" ~ as.double(low+not_detected),
                                   level == "Low" ~ as.double(not_detected),
                                   level == "Not detected" ~ 0)) %>% 
    mutate(samples_noChange = case_when(level == "High" ~ as.double(high),
                                   level == "Medium" ~ as.double(medium),
                                   level == "Low" ~ as.double(low),
                                   level == "Not detected" ~ as.double(not_detected))) %>% 
    filter(samples_down >= 0.5*n_samples) %>% 
    filter(tissue == tissue_type) %>% 
    filter(cancer == cancer_type) %>% 
    dplyr::select(gene)
    # dplyr::select(gene_name)
}

checkIfUpregulated <- function(tissue_type, cancer_type, normal_data, cancer_data){
  
  inner_join(normal_data, cancer_data, by = "gene") %>%
    dplyr::select(gene, gene_name = gene_name.x, tissue, cancer, level, high:not_detected, n_samples) %>% 
    mutate(samples_up = case_when(level == "High" ~ 0,
                                   level == "Medium" ~ as.double(high),
                                   level == "Low" ~ as.double(high+medium),
                                   level == "Not detected" ~ as.double(high+medium+low))) %>% 
    mutate(samples_down = case_when(level == "High" ~ as.double(medium+low+not_detected),
                                   level == "Medium" ~ as.double(low+not_detected),
                                   level == "Low" ~ as.double(not_detected),
                                   level == "Not detected" ~ 0)) %>% 
    mutate(samples_noChange = case_when(level == "High" ~ as.double(high),
                                   level == "Medium" ~ as.double(medium),
                                   level == "Low" ~ as.double(low),
                                   level == "Not detected" ~ as.double(not_detected))) %>% 
    filter(samples_up >= 0.5*n_samples) %>% 
    filter(tissue == tissue_type) %>% 
    filter(cancer == cancer_type) %>%
    dplyr::select("gene")
    # dplyr::select("gene_name")
}
```

